version: '3'
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./external/postgresql:/var/lib/postgresql/data
#      - db:/var/lib/postgresql/data

networks:
  main:
    driver: bridge
