version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../snode/migrations/V1__init.sql:/snode/migrations/V1__init.sql
      - ../snode/migrations/V2___sampleData.sql:/snode/migrations/V2___sampleData.sql
      - ../vnode/migrations/V1__init.sql:/vnode/migrations/V1__init.sql
      - ../vnode/migrations/V2___sampleData.sql:/vnode/migrations/V2___sampleData.sql
      - ./dstorage_populate.sh:/dstorage_populate.sh
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  dbsetup:
    image: postgres:14
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../snode/migrations/V1__init.sql:/snode/migrations/V1__init.sql
      - ../snode/migrations/V2___sampleData.sql:/snode/migrations/V2___sampleData.sql
      - ../vnode/migrations/V1__init.sql:/vnode/migrations/V1__init.sql
      - ../vnode/migrations/V2___sampleData.sql:/vnode/migrations/V2___sampleData.sql
      - ./dstorage_populate.sh:/dstorage_populate.sh
    command: sh -c "/dstorage_populate.sh"

  vnode1:
    image: vnodeimage
    depends_on:
      db:
        condition: service_healthy
      dbsetup:
        condition: service_completed_successfully
    environment:
      - "NODE_ENV='development'"
      - "PORT=4000"
      - "RUNNING_ON_MACHINE=mac"
      - "LOG_LEVEL='debug'"
      - "SERVER_ENV=DEV"
      - "DB_HOST=db"
      - "DB_NAME=vnode1"
      - "DB_USER=postgres"
      - "DB_PASS=postgres"
      - "VNODE_READ_QUORUM=3"
      - "VNODE_WRITE_QUORUM=4"

    ports:
      - '4000:4000'


  snode1:
    image: snodeimage
    depends_on:
      db:
        condition: service_healthy
      dbsetup:
        condition: service_completed_successfully
    environment:
      - "NODE_ENV='development'"
      - "PORT=3000"
      - "RUNNING_ON_MACHINE=mac"
      - "LOG_LEVEL='debug'"
      - "SERVER_ENV=DEV"
      - "DB_HOST=db"
      - "DB_NAME=snode1"
      - "DB_USER=postgres"
      - "DB_PASS=postgres"
      - "TEST_VNODE1_API_URL=http://vnode1:4000" 
      - "TEST_SNODE_API_URL=http://snode1:3000" 
      - "TEST_SNODE_DB_USER=postgres"
      - "TEST_SNODE_DB_PASS=postgres" 
      - "TEST_SNODE_DB_HOST=db" 
      - "TEST_SNODE_DB_NAME=snode1"

    ports:
      - '3000:3000'

  snode2:
      image: snodeimage
      depends_on:
        db:
          condition: service_healthy
        dbsetup:
          condition: service_completed_successfully
      environment:
        - "NODE_ENV='development'"
        - "PORT=3001"
        - "RUNNING_ON_MACHINE=mac"
        - "LOG_LEVEL='debug'"
        - "SERVER_ENV=DEV"
        - "DB_HOST=db"
        - "DB_NAME=snode2"
        - "DB_USER=postgres"
        - "DB_PASS=postgres"
        - "TEST_VNODE1_API_URL=http://vnode1:4000" 
        - "TEST_SNODE_API_URL=http://snode2:3001" 
        - "TEST_SNODE_DB_USER=postgres"
        - "TEST_SNODE_DB_PASS=postgres" 
        - "TEST_SNODE_DB_HOST=db" 
        - "TEST_SNODE_DB_NAME=snode2"

      ports:
        - '3001:3001'
    
  snode3:
      image: snodeimage
      depends_on:
        db:
          condition: service_healthy
        dbsetup:
          condition: service_completed_successfully
      environment:
        - "NODE_ENV='development'"
        - "PORT=3002"
        - "RUNNING_ON_MACHINE=mac"
        - "LOG_LEVEL='debug'"
        - "SERVER_ENV=DEV"
        - "DB_HOST=db"
        - "DB_NAME=snode3"
        - "DB_USER=postgres"
        - "DB_PASS=postgres"
        - "TEST_VNODE1_API_URL=http://vnode1:4000"
        - "TEST_SNODE_API_URL=http://snode3:3002"
        - "TEST_SNODE_DB_USER=postgres"
        - "TEST_SNODE_DB_PASS=postgres"
        - "TEST_SNODE_DB_HOST=db"
        - "TEST_SNODE_DB_NAME=snode3"

      ports:
        - '3002:3002'
      
  snode4:
      image: snodeimage
      depends_on:
        db:
          condition: service_healthy
        dbsetup:
          condition: service_completed_successfully
      environment:
        - "NODE_ENV='development'"
        - "PORT=3003"
        - "RUNNING_ON_MACHINE=mac"
        - "LOG_LEVEL='debug'"
        - "SERVER_ENV=DEV"
        - "DB_HOST=db"
        - "DB_NAME=snode4"
        - "DB_USER=postgres"
        - "DB_PASS=postgres"
        - "TEST_VNODE1_API_URL=http://vnode1:4000"
        - "TEST_SNODE_API_URL=http://snode4:3003"
        - "TEST_SNODE_DB_USER=postgres"
        - "TEST_SNODE_DB_PASS=postgres"
        - "TEST_SNODE_DB_HOST=db"
        - "TEST_SNODE_DB_NAME=snode4"

      ports:
        - '3003:3003'